/**
 * Prisma schema → typed walcast events. Pure text-in, text-out codegen:
 * no Prisma runtime, no walcast runtime, nothing to import at runtime at
 * all — the generated file is self-contained.
 *
 * Types are honest about what pgoutput actually delivers (text-format
 * tuples decoded conservatively): BigInt and Decimal arrive as strings,
 * DateTime as Postgres text timestamps, lists as Postgres array literals.
 */

interface ParsedField {
  /** Column name as it appears in events (@map respected). */
  column: string
  tsType: string
  optional: boolean
}

interface ParsedModel {
  /** Table name as it appears in events (@@map respected). */
  table: string
  /** TS-friendly name (the Prisma model name). */
  model: string
  fields: ParsedField[]
}

interface ParsedEnum {
  name: string
  values: string[]
}

const SCALARS: Record<string, string> = {
  String: 'string',
  Boolean: 'boolean',
  Int: 'number',
  Float: 'number',
  // int8 can exceed Number.MAX_SAFE_INTEGER; walcast delivers it as string.
  BigInt: 'string',
  // numeric loses precision as a float; walcast delivers it as string.
  Decimal: 'string',
  // Postgres text form, e.g. "2026-07-19 12:00:00+00".
  DateTime: 'string',
  Json: 'JsonValue',
  Bytes: 'string',
  Unsupported: 'string',
}

/**
 * Extract `keyword Name { body }` blocks with a brace-depth scan. A naive
 * `\{[^}]*\}` regex truncates at the first `}` inside an attribute string —
 * `@default("{}")` is enough to silently drop every following field.
 */
function extractBlocks(text: string, keyword: string): Array<{ name: string; body: string }> {
  const out: Array<{ name: string; body: string }> = []
  const open = new RegExp(`(?:^|\\n)\\s*${keyword}\\s+(\\w+)\\s*\\{`, 'g')
  let match
  while ((match = open.exec(text)) !== null) {
    let depth = 1
    let inString = false
    let i = open.lastIndex
    for (; i < text.length && depth > 0; i++) {
      const c = text[i]
      if (inString) {
        if (c === '\\') i++
        else if (c === '"') inString = false
      } else if (c === '"') inString = true
      else if (c === '{') depth++
      else if (c === '}') depth--
    }
    out.push({ name: match[1]!, body: text.slice(open.lastIndex, i - 1) })
    open.lastIndex = i
  }
  return out
}

export function parsePrismaSchema(source: string): { models: ParsedModel[]; enums: ParsedEnum[] } {
  const text = source.replace(/\/\/.*$/gm, '')
  const enums: ParsedEnum[] = []
  for (const block of extractBlocks(text, 'enum')) {
    const values: string[] = []
    for (const raw of block.body.split('\n')) {
      const line = raw.trim()
      if (!line || line.startsWith('@')) continue
      const [name] = line.split(/\s+/)
      if (!name) continue
      // Events carry database values, so an enum value's @map wins.
      const mapped = /@map\(\s*"([^"]+)"\s*\)/.exec(line)
      values.push(mapped ? mapped[1]! : name)
    }
    enums.push({ name: block.name, values })
  }
  const enumNames = new Set(enums.map((e) => e.name))

  const modelBlocks = extractBlocks(text, 'model')
  const modelNames = new Set(modelBlocks.map((m) => m.name))

  const models: ParsedModel[] = []
  for (const block of modelBlocks) {
    const model = block.name
    const body = block.body
    let table = model
    const tableMap = /@@map\(\s*"([^"]+)"\s*\)/.exec(body)
    if (tableMap) table = tableMap[1]!

    const fields: ParsedField[] = []
    for (const raw of body.split('\n')) {
      const line = raw.trim()
      if (!line || line.startsWith('@@')) continue
      const m = /^(\w+)\s+(\w+)(\[\])?(\?)?/.exec(line)
      if (!m) continue
      const [, name, type, isList, isOptional] = m
      if (modelNames.has(type!) || line.includes('@relation')) continue // relation, not a column

      let column = name!
      const colMap = /@map\(\s*"([^"]+)"\s*\)/.exec(line)
      if (colMap) column = colMap[1]!

      let tsType: string
      if (enumNames.has(type!)) tsType = type!
      else tsType = SCALARS[type!] ?? 'string'
      // Postgres arrays arrive as text literals ("{a,b}") — see the docs.
      if (isList) tsType = 'string'

      fields.push({ column, tsType, optional: Boolean(isOptional) })
    }
    models.push({ table, model, fields })
  }
  return { models, enums }
}

export function generate(source: string): string {
  const { models, enums } = parsePrismaSchema(source)
  const lines: string[] = [
    '/* Generated by @walcast/typegen-prisma — do not edit.',
    ' * Rows are typed as walcast delivers them (pgoutput text tuples):',
    ' * BigInt/Decimal as strings, DateTime as Postgres text, lists as array literals. */',
    '',
    'export type JsonValue = string | number | boolean | null | { [key: string]: JsonValue } | JsonValue[]',
    '',
  ]
  for (const e of enums) {
    lines.push(`export type ${e.name} = ${e.values.map((v) => `'${v}'`).join(' | ')}`, '')
  }
  for (const m of models) {
    lines.push(`export interface ${m.model}Row {`)
    for (const f of m.fields) {
      const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(f.column) ? f.column : `'${f.column}'`
      lines.push(`  ${key}: ${f.tsType}${f.optional ? ' | null' : ''}`)
    }
    lines.push('}', '')
  }
  lines.push('export interface WalcastTables {')
  for (const m of models) lines.push(`  '${m.table}': ${m.model}Row`)
  lines.push('}', '')
  lines.push(
    `export interface ChangeEvent<Row = Record<string, unknown>> {`,
    `  id: string`,
    `  lsn: string`,
    `  commit_lsn: string`,
    `  commit_time: string`,
    `  schema: string`,
    `  table: string`,
    `  op: 'insert' | 'update' | 'delete' | 'truncate'`,
    `  before: Row | null`,
    `  after: Row | null`,
    `}`,
    ``,
    `export type WalcastEvent<T extends keyof WalcastTables = keyof WalcastTables> =`,
    `  ChangeEvent<WalcastTables[T]> & { table: T }`,
    ``,
    `/** Narrow an event to a table: \`if (isChange(e, 'users')) e.after?.email\` */`,
    `export function isChange<T extends keyof WalcastTables>(`,
    `  event: ChangeEvent<unknown>,`,
    `  table: T,`,
    `): event is WalcastEvent<T> {`,
    `  return event.table === table`,
    `}`,
    ``,
  )
  return lines.join('\n')
}
