/* Generated by @walcast/typegen-prisma — do not edit.
 * Rows are typed as walcast delivers them (pgoutput text tuples):
 * BigInt/Decimal as strings, DateTime as Postgres text, lists as array literals. */

export type JsonValue =
  string | number | boolean | null | { [key: string]: JsonValue } | JsonValue[]

export interface UserRow {
  id: string
  email: string
  name: string | null
  metadata: JsonValue
  created_at: string
}

export interface WalcastTables {
  users: UserRow
}

export interface ChangeEvent<Row = Record<string, unknown>> {
  id: string
  lsn: string
  commit_lsn: string
  commit_time: string
  schema: string
  table: string
  op: 'insert' | 'update' | 'delete' | 'truncate'
  before: Row | null
  after: Row | null
}

export type WalcastEvent<T extends keyof WalcastTables = keyof WalcastTables> = ChangeEvent<
  WalcastTables[T]
> & { table: T }

/** Narrow an event to a table: `if (isChange(e, 'users')) e.after?.email` */
export function isChange<T extends keyof WalcastTables>(
  event: ChangeEvent<unknown>,
  table: T,
): event is WalcastEvent<T> {
  return event.table === table
}
